package drift

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type RemediationRecipe struct {
	Layer         string `json:"layer"`
	Address       string `json:"address"`
	Type          string `json:"type"`
	RevertCommand string `json:"revert_command"`
	AcceptCommand string `json:"accept_command"`
	AuditCommand  string `json:"audit_command,omitempty"`
}

// GenerateRemediationRecipes builds actionable copy-paste commands for detected changes.
func GenerateRemediationRecipes(results []ScanResult, engineBinary string) []RemediationRecipe {
	if engineBinary == "" {
		engineBinary = "terraform"
	}

	var recipes []RemediationRecipe

	for _, res := range results {
		if res.Err != nil {
			continue
		}

		for _, drift := range res.Drifts {
			// For both EXTERNAL_DRIFT and PLANNED_CHANGE, target apply reverts or pushes code
			revertCmd := fmt.Sprintf("%s apply -target='%s'", engineBinary, drift.Address)
			acceptCmd := fmt.Sprintf("%s apply -refresh-only -target='%s'", engineBinary, drift.Address)

			var auditCmd string
			if strings.HasPrefix(drift.Type, "aws_") {
				// Generate CloudTrail event lookup query template
				resourceName := drift.Address
				if parts := strings.Split(drift.Address, "."); len(parts) > 1 {
					resourceName = parts[len(parts)-1]
				}
				auditCmd = fmt.Sprintf("aws cloudtrail lookup-events --lookup-attributes AttributeKey=ResourceName,AttributeValue='%s'", resourceName)
			}

			recipes = append(recipes, RemediationRecipe{
				Layer:         res.Path,
				Address:       drift.Address,
				Type:          drift.Type,
				RevertCommand: revertCmd,
				AcceptCommand: acceptCmd,
				AuditCommand:  auditCmd,
			})
		}
	}

	return recipes
}

// ExportRemediationScript writes an executable bash script containing all remediation commands.
func ExportRemediationScript(path string, results []ScanResult, engineBinary string) error {
	recipes := GenerateRemediationRecipes(results, engineBinary)

	var sb strings.Builder
	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("# Generated by tf-drift remediation recipe generator\n")
	sb.WriteString("# Review targets before executing.\n\n")
	sb.WriteString("set -euo pipefail\n\n")

	currentLayer := ""
	for _, r := range recipes {
		if r.Layer != currentLayer {
			currentLayer = r.Layer
			_, _ = fmt.Fprintf(&sb, "# ───────────────────────────────────────────────\n")
			_, _ = fmt.Fprintf(&sb, "# Layer: %s\n", currentLayer)
			_, _ = fmt.Fprintf(&sb, "# ───────────────────────────────────────────────\n")
			_, _ = fmt.Fprintf(&sb, "pushd \"%s\" > /dev/null\n\n", currentLayer)
		}

		_, _ = fmt.Fprintf(&sb, "# Target: %s (%s)\n", r.Address, r.Type)
		if r.AuditCommand != "" {
			_, _ = fmt.Fprintf(&sb, "# Audit who changed it:\n# %s\n", r.AuditCommand)
		}
		_, _ = fmt.Fprintf(&sb, "# Option A: Revert infrastructure to match code\n")
		_, _ = fmt.Fprintf(&sb, "# %s\n\n", r.RevertCommand)
		_, _ = fmt.Fprintf(&sb, "# Option B: Accept live infrastructure into state\n")
		_, _ = fmt.Fprintf(&sb, "# %s\n\n", r.AcceptCommand)
	}

	if currentLayer != "" {
		sb.WriteString("popd > /dev/null\n")
	}

	dir := filepath.Dir(path)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory for remediation script: %w", err)
		}
	}

	if err := os.WriteFile(path, []byte(sb.String()), 0755); err != nil {
		return fmt.Errorf("failed to write remediation script: %w", err)
	}

	return nil
}
